### ISSUE TITLE
Feature request :

### ISSUE THREAD

**Issue by userrand** [JerryI/wolfram-js-frontend#30]
I learned how to use vim not too long ago and probably like many vim users, anything other than vim is tedious. As i understand neovim is made to be embeddable so maybe it is possible to use neovim to handle the editing. 

An example of using neovim in an electron app is the neovim extension of vscode (currently I am just using the vim extension). An example of vim in the browser is https://github.com/ajaxorg/ace

**Comment by JerryI** [comment]
Plugin system doesn’t have GUI for now, but it is about to be done.

I would suggest to make as wljs-package using plugin [vimmode](https://github.com/replit/codemirror-vim)

**Comment by JerryI** [comment]
Since editor is modular, its extensions are exposed in `window.EditorExtensions` array.

In principle, it should work, when you just create a single file in the plugins folder

![Screenshot 2023-09-01 at 11 15 41](https://github.com/JerryI/wolfram-js-frontend/assets/4111822/b95c0022-e2f5-4acc-9349-bc7c62bed0b7)

But then in my case it throws an error ;)

```
kernel.js:2017 Uncaught (in promise) Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
    at inner (kernel.js:2017:23)
    at inner (kernel.js:1992:17)
    at inner (kernel.js:1992:17)
    at flatten (kernel.js:2021:5)
    at Configuration.resolve (kernel.js:1929:25)
    at EditorState.create (kernel.js:2756:43)
    at new EditorView (kernel.js:10643:68)
    at new CodeMirrorCell (kernel.js:71492:22)
    at new CellWrapper (kernel.js:6948:22)
    at core.FrontEndCreateCell (kernel.js:7103:5)
```

That usually happens, when an extension (vimmode) uses slightly different version of the modules from which the main editor was built. This is very annoying, actually. 


I will try to update all components to the latest versions and poke this VIM mode extension plugin a few more times.
